### ISSUE TITLE
php artisan vendor:publish does not work.

### ISSUE THREAD

**Issue by mrmrn** [halaei/telegram-bot#3]
I created a new laravel 5.4 project.
I used this command for your package:
`composer require halaei/telegram-bot`
then I added `        Telegram\Bot\Laravel\TelegramServiceProvider::class,`  to ServiceProviders. 
then I used `php artisan vendor:publish --provider="Telegram\Bot\Laravel\TelegramServiceProvider"` and `php artisan vendor:publish` and both give me the same error:
` [Symfony\Component\Debug\Exception\FatalThrowableError]         
  Class 'Telegram\Bot\Laravel\TelegramServiceProvider' not found  `

**Comment by halaei** [comment]
Please note that this repository is a fork of [irazasyed/telegram-bot-sdk](https://github.com/irazasyed/telegram-bot-sdk). The code is almost identical, except that I removed some features to make maintenance and bug-fixes and development of new features easier. The service provider is among the removed features because it really didn't do that much! If you need an instance of `Telegram\Bot\Api`, simply call the constructor or inject it into other objects:

```php
use \Telegram\Bot\Api;
$api = new Api();//identical to new Api(getenv('TELEGRAM_BOT_TOKEN'));
$api->sendPhoto([...]);
```

I think this issue means that this repository needs some documentation. So I don't close the issue for now.

**Comment by mrmrn** [comment]
ممنون
